# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Build and Deploy to Bitpoke App

on:
  # Uncomment to deploy when pushing on the main branch
  # push:
  #   branches:
  #     - main

  # By default run manually
  workflow_dispatch:
env:
  BITPOKE_PROJECT: ${{ vars.BITPOKE_PROJECT }}
  BITPOKE_SITE_NAME: ${{ vars.BITPOKE_SITE_NAME }}
  GOOGLE_CLOUD_PROJECT: ${{ vars.GOOGLE_CLOUD_PROJECT }}
  GOOGLE_CLOUD_ZONE: ${{ vars.GOOGLE_CLOUD_ZONE }}
  GOOGLE_KUBERNETES_ENGINE_CLUSTER: ${{ vars.GOOGLE_KUBERNETES_ENGINE_CLUSTER }}
  GCR_IMAGE: ${{ vars.GCR_IMAGE }}

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
      with:
        credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_DATA }}

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@aa5489c8933f4cc7a4f7d45035b3b1440c9c10db # v3.0.1
      with:
        project_id: ${{ env.GOOGLE_CLOUD_PROJECT }}

    # Configure Docker to use the gcloud command-line tool as a credential
    # helper for authentication
    - run: |-
        gcloud --quiet auth configure-docker

    # Build the Docker image
    - name: Build
      run: |-
        docker build \
          --tag "$GCR_IMAGE:$GITHUB_SHA" \
          .

    # Push the Docker image to Google Container Registry
    - name: Publish
      run: |-
        docker push "$GCR_IMAGE:$GITHUB_SHA"


    # Get the GKE credentials so we can deploy to the cluster
    - uses: google-github-actions/get-gke-credentials@3da1e46a907576cefaa90c484278bb5b259dd395 # v3.0.0
      with:
        cluster_name: ${{ env.GOOGLE_KUBERNETES_ENGINE_CLUSTER }}
        location: ${{ env.GOOGLE_CLOUD_ZONE }}
        project_id: ${{ env.GOOGLE_CLOUD_PROJECT }}


    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: 'kubectl -n $BITPOKE_PROJECT patch wordpress $BITPOKE_SITE_NAME --type=json -p "[{\"op\": \"replace\", \"path\": \"/spec/image\", \"value\": \"$GCR_IMAGE:$GITHUB_SHA\"}]"'
